const { Pool } = require('pg');
const pool = new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('localhost')?false:{rejectUnauthorized:false}});
const headers={Authorization:`Discogs token=${process.env.DISCOGS_API_TOKEN}`, 'User-Agent':'VinylCatalog/1.0 (personal collection)','Accept':'application/json'};
let nextAt=0;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function get(url,retries=0){const w=Math.max(0,nextAt-Date.now());if(w)await wait(w);const r=await fetch(url,{headers});nextAt=Date.now()+1100;const rem=Number(r.headers.get('x-discogs-ratelimit-remaining'));if(Number.isFinite(rem)&&rem<=2)nextAt=Date.now()+5000;if(r.status===429&&retries<5){const ra=Number(r.headers.get('retry-after'));nextAt=Date.now()+(Number.isFinite(ra)?ra*1000:Math.min(60000,2000*2**retries));return get(url,retries+1)}if(!r.ok)throw Error(`Discogs HTTP ${r.status}`);return r.json()}
const norm=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const artistNorm=s=>norm(s).replace(/^(the|a)\s+/,'');
function score(record,c){const a=artistNorm(record.artist),t=norm(record.album);const title=norm(c.title||'');const ca=artistNorm(c.artist||c.artists?.map(x=>x.name).join(' ')||'');let s=0;const exactTitle=title===t||title.replace(/\s+\(.*\)$/,'')===t;if(exactTitle)s+=100;else if(title.includes(t))s+=55;if(ca===a||ca.includes(a)||a.includes(ca))s+=70;if(title.includes(a))s+=35;if(record.year&&c.year){const y=Number(c.year),r=Number(record.year);if(y===r)s+=25;else if(Math.abs(y-r)<=1)s+=8;else s-=15}return s}
function extractStyles(detail){return Array.isArray(detail.styles)?detail.styles.slice(0,2).join('/'):(Array.isArray(detail.style)?detail.style.slice(0,2).join('/'):null)}
async function search(record,type,params){const u=new URL('https://api.discogs.com/database/search');u.searchParams.set('type',type);u.searchParams.set('per_page','20');for(const [k,v] of Object.entries(params))u.searchParams.set(k,v);const d=await get(u.toString());return Array.isArray(d.results)?d.results:[]}
async function resolve(record){let candidates=[];let type='master';
for(const params of [
 {artist:record.artist,release_title:record.album},
 {q:`${record.artist} ${record.album}`},
 {release_title:record.album}
]){candidates.push(...(await search(record,'master',params)).map(c=>({...c,_type:'master'})));}
let unique=[...new Map(candidates.map(c=>[`${c._type}:${c.id}`,c])).values()];let ranked=unique.map(c=>({...c,_score:score(record,c)})).sort((a,b)=>b._score-a._score);
if(!ranked.length||ranked[0]._score<125){for(const params of [{artist:record.artist,release_title:record.album},{q:`${record.artist} ${record.album}`}])candidates.push(...(await search(record,'release',params)).map(c=>({...c,_type:'release'})));unique=[...new Map(candidates.map(c=>[`${c._type}:${c.id}`,c])).values()];ranked=unique.map(c=>({...c,_score:score(record,c)})).sort((a,b)=>b._score-a._score);}
if(!ranked.length)return {status:'no_match',confidence:'none',reason:'No Discogs candidates found after expanded search'};
const best=ranked[0],second=ranked[1];
if(best._score<125)return {status:'ambiguous',confidence:'low',reason:`Expanded search did not produce a sufficiently strong match (score ${best._score})`};
if(second&&second._score>=best._score-10&&second._score>=125)return {status:'ambiguous',confidence:'medium',reason:'Expanded search still produced multiple near-equal candidates'};
type=best._type;const detail=await get(`https://api.discogs.com/${type}s/${best.id}`);let styles=extractStyles(detail);
if(!styles&&type==='master'){const releases=Array.isArray(detail.releases)?detail.releases:[];const r=releases[0];if(r?.id){const rd=await get(`https://api.discogs.com/releases/${r.id}`);styles=extractStyles(rd)}}
return {status:styles?'matched':'matched_no_style',styles:styles||null,discogs_id:Number(best.id),discogs_type:type,discogs_url:`https://www.discogs.com/${type}/${best.id}`,matched_artist:detail.artists?.map(a=>a.name).join(', ')||best.artist||best.title,matched_title:detail.title||best.title,matched_year:detail.year||best.year||null,confidence:best._score>=170?'high':'medium',reason:`Expanded Discogs match; score ${best._score}`};}
async function save(id,r){await pool.query(`UPDATE discogs_style_audit SET status=$2,styles=$3,discogs_id=$4,discogs_type=$5,discogs_url=$6,matched_artist=$7,matched_title=$8,matched_year=$9,confidence=$10,reason=$11,checked_at=NOW(),updated_at=NOW() WHERE record_id=$1`,[id,r.status,r.styles||null,r.discogs_id||null,r.discogs_type||null,r.discogs_url||null,r.matched_artist||null,r.matched_title||null,r.matched_year||null,r.confidence||null,r.reason||null]);}
async function main(){if(!process.env.DISCOGS_API_TOKEN){console.log('Discogs token not configured; skipping resolver');return}await pool.query(`CREATE TABLE IF NOT EXISTS app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL)`);const marker=await pool.query("SELECT value FROM app_meta WHERE key='discogs_unresolved_resolve_v2'");if(marker.rows[0]?.value==='complete'){console.log('Discogs unresolved resolver already complete');return}await pool.query("INSERT INTO app_meta(key,value)VALUES('discogs_unresolved_resolve_v2','running') ON CONFLICT(key) DO UPDATE SET value='running'");const {rows}=await pool.query("SELECT r.id,r.artist,r.album,r.year FROM records r JOIN discogs_style_audit a ON a.record_id=r.id WHERE a.status IN ('ambiguous','no_match') ORDER BY r.id");console.log(`Resolving ${rows.length} unresolved Discogs audit records`);for(const r of rows){try{const result=await resolve(r);await save(r.id,result);console.log(`${r.id} ${r.artist} — ${r.album}: ${result.status} ${result.styles||''}`)}catch(e){console.error(`Resolver error ${r.id}:`,e.message)}}
const dateMarker=await pool.query("SELECT value FROM app_meta WHERE key='date_corrections_v1'");if(dateMarker.rows[0]?.value!=='complete'){const dates={65:2015,73:2024,76:2025,54:1963,229:2019,236:1994,238:2011,242:1989};for(const [id,year] of Object.entries(dates))await pool.query('UPDATE records SET year=$1,updated_at=NOW() WHERE id=$2',[year,id]);await pool.query("INSERT INTO app_meta(key,value)VALUES('date_corrections_v1','complete') ON CONFLICT(key) DO UPDATE SET value='complete'");console.log('Applied 8 approved original-publication date corrections');}
await pool.query("INSERT INTO app_meta(key,value)VALUES('discogs_unresolved_resolve_v2','complete') ON CONFLICT(key) DO UPDATE SET value='complete'");console.log('Discogs unresolved resolver complete');}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>pool.end());
