const express=require('express');const{Pool}=require('pg');const path=require('path');const crypto=require('crypto');
const app=express(),PORT=process.env.PORT||10000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('localhost')?false:{rejectUnauthorized:false}});
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const COOKIE='vinyl_admin';
function sign(v){return crypto.createHmac('sha256',process.env.SESSION_SECRET||'').update(v).digest('base64url')}
function makeSession(){const p=Buffer.from(JSON.stringify({u:process.env.ADMIN_USERNAME,exp:Date.now()+8*60*60*1000})).toString('base64url');return p+'.'+sign(p)}
function admin(req){const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!raw)return false;const[a,b]=raw.split('.');if(!a||!b||!process.env.SESSION_SECRET)return false;try{if(!crypto.timingSafeEqual(Buffer.from(b),Buffer.from(sign(a))))return false;const p=JSON.parse(Buffer.from(a,'base64url').toString());return p.u===process.env.ADMIN_USERNAME&&p.exp>Date.now()}catch{return false}}
function requireAdmin(req,res,next){if(!admin(req))return res.status(401).json({error:'Admin login required'});next()}
app.get('/api/auth/status',(req,res)=>res.json({admin:admin(req)}));
app.post('/api/auth/login',(req,res)=>{const{username,password}=req.body||{};if(username===process.env.ADMIN_USERNAME&&password===process.env.ADMIN_PASSWORD){res.setHeader('Set-Cookie',`${COOKIE}=${makeSession()}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800`);return res.json({admin:true})}res.status(401).json({error:'Invalid username or password'})});
app.post('/api/auth/logout',(req,res)=>{res.setHeader('Set-Cookie',`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`);res.json({admin:false})});
const PERSON_ARTISTS=['Alice Coltrane','Amy Winehouse','Andrew Bird','Antonín Dvořák','Beck','Bill Callahan','Björk','Brittany Howard','Caribou','Charles Mingus','Courtney Barnett','Curtis Mayfield',"D'Angelo",'Dave Brubeck','David Bowie','Elton John','Erykah Badu','Father John Misty','Fiona Apple','Frank Ocean','Freddie Hubbard','George Clanton','Helado Negro','Iggy Pop','James Brown','John Coltrane','Kali Uchis','Kamasi Washington','Kendrick Lamar','Kurt Vile','Lana Del Rey','Lou Reed','Marvin Gaye','Meshell Ndegeocello','Michael Jackson','Miles Davis','Mingus','Neon Indian','Nilüfer Yanya','Nina Simone','Paul Simon','Prince','Ryuichi Sakamoto','Sade','Sam Cooke','Snail Mail','St. Vincent','Stevie Wonder','Thundercat','Tom Petty','Toro y Moi','Tycho','Tó Trips','Washed Out','Yaeji','Yo-Yo Ma'];
async function ensureDatabase(){await pool.query(`CREATE TABLE IF NOT EXISTS records(id BIGSERIAL PRIMARY KEY,artist TEXT NOT NULL,album TEXT NOT NULL,year INTEGER,genre TEXT,notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());ALTER TABLE records ADD COLUMN IF NOT EXISTS notes TEXT;ALTER TABLE records ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();ALTER TABLE records ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();ALTER TABLE records ADD COLUMN IF NOT EXISTS artist_type TEXT NOT NULL DEFAULT 'Group/Artist';CREATE TABLE IF NOT EXISTS app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS discogs_style_audit(record_id BIGINT PRIMARY KEY REFERENCES records(id) ON DELETE CASCADE,status TEXT NOT NULL,styles TEXT,discogs_id BIGINT,discogs_type TEXT,discogs_url TEXT,matched_artist TEXT,matched_title TEXT,matched_year INTEGER,confidence TEXT,reason TEXT,checked_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS idx_records_artist ON records(artist);CREATE INDEX IF NOT EXISTS idx_records_album ON records(album);CREATE INDEX IF NOT EXISTS idx_records_year ON records(year);CREATE INDEX IF NOT EXISTS idx_records_genre ON records(genre);CREATE INDEX IF NOT EXISTS idx_discogs_audit_status ON discogs_style_audit(status);`);const marker=await pool.query("SELECT 1 FROM app_meta WHERE key='artist_type_seed_v1'");if(!marker.rowCount){await pool.query(`UPDATE records SET artist_type='Person' WHERE LOWER(artist)=ANY($1::text[])`,[PERSON_ARTISTS.map(x=>x.toLowerCase())]);await pool.query("INSERT INTO app_meta(key,value)VALUES('artist_type_seed_v1','complete')")}}
function csvEscape(value){const s=value==null?'':String(value);return /[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function norm(s){return String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}
function artistNorm(s){return norm(s).replace(/^(the|a)\s+/,'')}
function discogsHeaders(){return {'Authorization':`Discogs token=${process.env.DISCOGS_API_TOKEN}`,'User-Agent':'VinylCatalog/1.0 (personal collection)','Accept':'application/json'}}
let discogsNextRequestAt=0;
async function discogsGet(url,retries=0){if(!process.env.DISCOGS_API_TOKEN)throw Error('DISCOGS_API_TOKEN is not configured');const wait=Math.max(0,discogsNextRequestAt-Date.now());if(wait)await new Promise(r=>setTimeout(r,wait));const response=await fetch(url,{headers:discogsHeaders()});const limit=Number(response.headers.get('x-discogs-ratelimit'));const remaining=Number(response.headers.get('x-discogs-ratelimit-remaining'));discogsNextRequestAt=Date.now()+1100;if(Number.isFinite(limit)&&Number.isFinite(remaining)&&remaining<=2)discogsNextRequestAt=Date.now()+5000;if(response.status===429&&retries<5){const retryAfter=Number(response.headers.get('retry-after'));const backoff=Number.isFinite(retryAfter)?retryAfter*1000:Math.min(60000,2000*Math.pow(2,retries));discogsNextRequestAt=Date.now()+backoff;return discogsGet(url,retries+1)}if(!response.ok)throw Error(`Discogs HTTP ${response.status}`);return response.json()}
function scoreDiscogsCandidate(record,c){const a=artistNorm(record.artist),t=norm(record.album),title=norm(c.title||'');let score=0;if(title===`${a} ${t}`||title===`${norm(record.artist)} ${t}`)score+=70;if(title.includes(t))score+=20;if(title.includes(a))score+=20;if(record.year&&c.year){if(Number(record.year)===Number(c.year))score+=25;else if(Math.abs(Number(record.year)-Number(c.year))===1)score+=5;else score-=20}return score}
async function findDiscogsStyle(record){const base='https://api.discogs.com/database/search';let data=await discogsGet(`${base}?artist=${encodeURIComponent(record.artist)}&release_title=${encodeURIComponent(record.album)}&type=master&per_page=10`);let candidates=Array.isArray(data.results)?data.results:[];let type='master';if(!candidates.length){data=await discogsGet(`${base}?artist=${encodeURIComponent(record.artist)}&release_title=${encodeURIComponent(record.album)}&type=release&per_page=10`);candidates=Array.isArray(data.results)?data.results:[];type='release'}if(!candidates.length)return{status:'no_match',reason:'No Discogs search results'};const scored=candidates.map(c=>({...c,score:scoreDiscogsCandidate(record,c)})).sort((a,b)=>b.score-a.score);const best=scored[0],second=scored[1];if(best.score<80)return{status:'ambiguous',confidence:'low',reason:'No sufficiently strong artist/title/year match'};if(second&&second.score>=best.score-5)return{status:'ambiguous',confidence:'medium',reason:'Multiple Discogs candidates are too close to distinguish safely'};const detail=await discogsGet(`https://api.discogs.com/${type}s/${best.id}`);const styles=Array.isArray(detail.styles)?detail.styles.slice(0,2).join('/'):(Array.isArray(detail.style)?detail.style.slice(0,2).join('/'):null);return{status:styles?'matched':'matched_no_style',styles:styles||null,discogs_id:best.id,discogs_type:type,discogs_url:`https://www.discogs.com/${type}/${best.id}`,matched_artist:detail.artists?.map(a=>a.name).join(', ')||best.title,matched_title:detail.title||best.title,matched_year:detail.year||best.year||null,confidence:best.score>=110?'high':'medium',reason:styles?'Matched conservatively using artist, album, and year':'Discogs match found but no Style values were returned'}}
let discogsAuditRunning=false;
async function runDiscogsAudit(){if(discogsAuditRunning)return;discogsAuditRunning=true;try{await pool.query("INSERT INTO app_meta(key,value)VALUES('discogs_style_audit_v1','running') ON CONFLICT(key) DO UPDATE SET value='running'");while(true){const{rows}=await pool.query("SELECT r.id,r.artist,r.album,r.year FROM records r LEFT JOIN discogs_style_audit a ON a.record_id=r.id WHERE a.record_id IS NULL ORDER BY r.id LIMIT 1");if(!rows.length)break;const r=rows[0];let result;try{result=await findDiscogsStyle(r)}catch(e){result={status:'error',confidence:'none',reason:e.message||'Discogs request failed'}}await pool.query(`INSERT INTO discogs_style_audit(record_id,status,styles,discogs_id,discogs_type,discogs_url,matched_artist,matched_title,matched_year,confidence,reason,checked_at,updated_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NOW(),NOW()) ON CONFLICT(record_id) DO UPDATE SET status=EXCLUDED.status,styles=EXCLUDED.styles,discogs_id=EXCLUDED.discogs_id,discogs_type=EXCLUDED.discogs_type,discogs_url=EXCLUDED.discogs_url,matched_artist=EXCLUDED.matched_artist,matched_title=EXCLUDED.matched_title,matched_year=EXCLUDED.matched_year,confidence=EXCLUDED.confidence,reason=EXCLUDED.reason,checked_at=NOW(),updated_at=NOW()`,[r.id,result.status,result.styles||null,result.discogs_id||null,result.discogs_type||null,result.discogs_url||null,result.matched_artist||null,result.matched_title||null,result.matched_year||null,result.confidence||null,result.reason||null])}await pool.query("INSERT INTO app_meta(key,value)VALUES('discogs_style_audit_v1','complete') ON CONFLICT(key) DO UPDATE SET value='complete' ")}catch(e){await pool.query("INSERT INTO app_meta(key,value)VALUES('discogs_style_audit_v1',$1) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",[`error:${String(e.message||e).slice(0,400)}`])}finally{discogsAuditRunning=false}}
app.get('/api/records',async(_,res)=>{try{const{rows}=await pool.query("SELECT * FROM records ORDER BY LOWER(REGEXP_REPLACE(artist,'^(The |A )','')),LOWER(album)");res.json(rows)}catch(e){res.status(500).json({error:'Unable to load records'})}});
app.get('/api/export.csv',requireAdmin,async(_,res)=>{try{const{rows}=await pool.query('SELECT id,artist,album,year,genre,notes,artist_type FROM records ORDER BY LOWER(REGEXP_REPLACE(artist,\'^(The |A )\',\'\')),LOWER(album)');const headers=['ID','Artist','Album','Year','Genre','Notes','Artist Type'];const lines=[headers.join(',')];for(const r of rows)lines.push([r.id,r.artist,r.album,r.year,r.genre,r.notes,r.artist_type].map(csvEscape).join(','));res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="vinyl_collection.csv"');res.send('\uFEFF'+lines.join('\r\n')+'\r\n')}catch(e){res.status(500).json({error:'Unable to export collection'})}});
app.get('/api/admin/discogs/audit',requireAdmin,async(_,res)=>{try{const{rows}=await pool.query(`SELECT r.id,r.artist,r.album,r.year,r.genre,a.status,a.styles,a.discogs_id,a.discogs_type,a.discogs_url,a.matched_artist,a.matched_title,a.matched_year,a.confidence,a.reason,a.checked_at FROM records r LEFT JOIN discogs_style_audit a ON a.record_id=r.id ORDER BY r.id`);const total=rows.length,checked=rows.filter(r=>r.status).length;const summary={total,checked,pending:total-checked,matched:rows.filter(r=>r.status==='matched').length,matched_no_style:rows.filter(r=>r.status==='matched_no_style').length,ambiguous:rows.filter(r=>r.status==='ambiguous').length,no_match:rows.filter(r=>r.status==='no_match').length,error:rows.filter(r=>r.status==='error').length};const meta=await pool.query("SELECT value FROM app_meta WHERE key='discogs_style_audit_v1'");res.json({running:discogsAuditRunning,status:meta.rows[0]?.value||'not_started',summary,records:rows})}catch(e){res.status(500).json({error:'Unable to load Discogs audit'})}});
app.post('/api/admin/discogs/audit',requireAdmin,async(_,res)=>{if(!process.env.DISCOGS_API_TOKEN)return res.status(400).json({error:'DISCOGS_API_TOKEN is not configured'});const meta=await pool.query("SELECT value FROM app_meta WHERE key='discogs_style_audit_v1'");if(discogsAuditRunning||meta.rows[0]?.value==='running')return res.status(409).json({error:'Discogs audit is already running'});const{rows}=await pool.query('SELECT COUNT(*)::int AS pending FROM records r LEFT JOIN discogs_style_audit a ON a.record_id=r.id WHERE a.record_id IS NULL');if(!rows[0].pending)return res.json({started:false,status:'complete',message:'Discogs audit is already complete'});runDiscogsAudit();res.status(202).json({started:true,pending:rows[0].pending})});
app.post('/api/records',requireAdmin,async(req,res)=>{const{artist,album,year,genre,notes,artist_type}=req.body;if(!artist?.trim()||!album?.trim())return res.status(400).json({error:'Artist and album are required'});const type=artist_type==='Person'?'Person':'Group/Artist';try{const{rows}=await pool.query('INSERT INTO records(artist,album,year,genre,notes,artist_type)VALUES($1,$2,$3,$4,$5,$6)RETURNING *',[artist.trim(),album.trim(),year?Number(year):null,genre?.trim()||null,notes?.trim()||null,type]);res.status(201).json(rows[0])}catch(e){res.status(500).json({error:'Unable to add record'})}});
app.put('/api/records/bulk',requireAdmin,async(req,res)=>{const records=Array.isArray(req.body?.records)?req.body.records:[];if(!records.length)return res.json({updated:0});const c=await pool.connect();try{await c.query('BEGIN');for(const r of records){if(!r.id||!r.artist?.trim()||!r.album?.trim())throw Error('Artist and album are required');const type=r.artist_type==='Person'?'Person':'Group/Artist';await c.query('UPDATE records SET artist=$1,album=$2,year=$3,genre=$4,notes=$5,artist_type=$6,updated_at=NOW() WHERE id=$7',[r.artist.trim(),r.album.trim(),r.year?Number(r.year):null,r.genre?.trim()||null,r.notes?.trim()||null,type,r.id])}await c.query('COMMIT');res.json({updated:records.length})}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message||'Unable to save changes'})}finally{c.release()}});
app.put('/api/records/:id',requireAdmin,async(req,res)=>{const{artist,album,year,genre,notes,artist_type}=req.body;if(!artist?.trim()||!album?.trim())return res.status(400).json({error:'Artist and album are required'});const type=artist_type==='Person'?'Person':'Group/Artist';try{const{rows}=await pool.query('UPDATE records SET artist=$1,album=$2,year=$3,genre=$4,notes=$5,artist_type=$6,updated_at=NOW() WHERE id=$7 RETURNING *',[artist.trim(),album.trim(),year?Number(year):null,genre?.trim()||null,notes?.trim()||null,type,req.params.id]);if(!rows.length)return res.status(404).json({error:'Record not found'});res.json(rows[0])}catch(e){res.status(500).json({error:'Unable to update record'})}});
app.delete('/api/records/:id',requireAdmin,async(req,res)=>{try{const r=await pool.query('DELETE FROM records WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Record not found'});res.status(204).end()}catch(e){res.status(500).json({error:'Unable to delete record'})}});
app.get('/{*splat}',(_,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
(async()=>{try{await ensureDatabase();app.listen(PORT,()=>console.log(`Vinyl collection listening on ${PORT}`))}catch(e){console.error(e);process.exit(1)}})();