const express=require("express"),{Pool}=require("pg"),fs=require("fs"),path=require("path");
const app=express(),PORT=process.env.PORT||10000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes("localhost")?false:{rejectUnauthorized:false}});
app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
async function migrate(){await pool.query(fs.readFileSync(path.join(__dirname,"db/migrations/001_initial.sql"),"utf8"))}
function parseCSV(s){let a=s.replace(/^\uFEFF/,"").trim().split(/\r?\n/),h=a.shift().split(",");return a.map(line=>{let o=[],c="",q=false;for(let i=0;i<line.length;i++){let x=line[i];if(x=='"'){if(q&&line[i+1]=='"'){c+='"';i++}else q=!q}else if(x==","&&!q){o.push(c);c=""}else c+=x}o.push(c);let r={};h.forEach((x,i)=>r[x.trim()]=o[i]??"");return r})}
async function seed(){let {rows}=await pool.query("SELECT COUNT(*)::int count FROM records");if(rows[0].count)return;let data=parseCSV(fs.readFileSync(path.join(__dirname,"data/vinyl_catalog.csv"),"utf8")),c=await pool.connect();try{await c.query("BEGIN");for(const r of data)await c.query("INSERT INTO records(artist,album,year,genre,notes) VALUES($1,$2,$3,$4,$5)",[r.Artist,r.Album,r.Year?+r.Year:null,r.Genre||null,r.Notes||null]);await c.query("COMMIT")}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
app.get("/api/records",async(_,res)=>{try{let {rows}=await pool.query("SELECT * FROM records ORDER BY LOWER(REGEXP_REPLACE(artist,'^(The |A )','')),LOWER(album)");res.json(rows)}catch(e){res.status(500).json({error:"Unable to load records"})}});
app.post("/api/records",async(req,res)=>{let {artist,album,year,genre,notes}=req.body;if(!artist?.trim()||!album?.trim())return res.status(400).json({error:"Artist and album are required"});try{let {rows}=await pool.query("INSERT INTO records(artist,album,year,genre,notes) VALUES($1,$2,$3,$4,$5) RETURNING *",[artist.trim(),album.trim(),year?+year:null,genre?.trim()||null,notes?.trim()||null]);res.status(201).json(rows[0])}catch(e){res.status(500).json({error:"Unable to add record"})}});
app.put("/api/records/:id",async(req,res)=>{let {artist,album,year,genre,notes}=req.body;if(!artist?.trim()||!album?.trim())return res.status(400).json({error:"Artist and album are required"});try{let {rows}=await pool.query("UPDATE records SET artist=$1,album=$2,year=$3,genre=$4,notes=$5,updated_at=NOW() WHERE id=$6 RETURNING *",[artist.trim(),album.trim(),year?+year:null,genre?.trim()||null,notes?.trim()||null,req.params.id]);if(!rows.length)return res.status(404).json({error:"Record not found"});res.json(rows[0])}catch(e){res.status(500).json({error:"Unable to update record"})}});
app.delete("/api/records/:id",async(req,res)=>{try{let r=await pool.query("DELETE FROM records WHERE id=$1",[req.params.id]);if(!r.rowCount)return res.status(404).json({error:"Record not found"});res.status(204).end()}catch(e){res.status(500).json({error:"Unable to delete record"})}});
app.get("/{*splat}", (_, res) =>res.sendFile(path.join(__dirname, "public", "index.html")));
(async()=>{try{await migrate();await seed();app.listen(PORT,()=>console.log("Vinyl collection listening on "+PORT))}catch(e){console.error(e);process.exit(1)}})();
