const express=require('express');const{Pool}=require('pg');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const app=express(),PORT=process.env.PORT||10000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('localhost')?false:{rejectUnauthorized:false}});
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const COOKIE='vinyl_admin';
function sign(v){return crypto.createHmac('sha256',process.env.SESSION_SECRET||'').update(v).digest('base64url')}
function makeSession(){const p=Buffer.from(JSON.stringify({u:process.env.ADMIN_USERNAME,exp:Date.now()+8*60*60*1000})).toString('base64url');return p+'.'+sign(p)}
function admin(req){const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!raw)return false;const[a,b]=raw.split('.');if(!a||!b||!process.env.SESSION_SECRET)return false;try{if(!crypto.timingSafeEqual(Buffer.from(b),Buffer.from(sign(a))))return false;const p=JSON.parse(Buffer.from(a,'base64url').toString());return p.u===process.env.ADMIN_USERNAME&&p.exp>Date.now()}catch{return false}}
function requireAdmin(req,res,next){if(!admin(req))return res.status(401).json({error:'Admin login required'});next()}
app.get('/api/auth/status',(req,res)=>res.json({admin:admin(req)}));
app.post('/api/auth/login',(req,res)=>{const{username,password}=req.body||{};if(username===process.env.ADMIN_USERNAME&&password===process.env.ADMIN_PASSWORD){res.setHeader('Set-Cookie',`${COOKIE}=${makeSession()}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800`);return res.json({admin:true})}res.status(401).json({error:'Invalid username or password'})});
app.post('/api/auth/logout',(req,res)=>{res.setHeader('Set-Cookie',`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`);res.json({admin:false})});
async function ensureDatabase(){await pool.query(`CREATE TABLE IF NOT EXISTS records(id BIGSERIAL PRIMARY KEY,artist TEXT NOT NULL,album TEXT NOT NULL,year INTEGER,genre TEXT,notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());ALTER TABLE records ADD COLUMN IF NOT EXISTS notes TEXT;ALTER TABLE records ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();ALTER TABLE records ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();CREATE INDEX IF NOT EXISTS idx_records_artist ON records(artist);CREATE INDEX IF NOT EXISTS idx_records_album ON records(album);CREATE INDEX IF NOT EXISTS idx_records_year ON records(year);CREATE INDEX IF NOT EXISTS idx_records_genre ON records(genre);`)}
function parseCSV(s){const lines=s.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),h=lines.shift().split(',').map(x=>x.trim());return lines.map(line=>{let o=[],c='',q=false;for(let i=0;i<line.length;i++){const x=line[i];if(x==='"'){if(q&&line[i+1]==='"'){c+='"';i++}else q=!q}else if(x===','&&!q){o.push(c);c=''}else c+=x}o.push(c);const r={};h.forEach((x,i)=>r[x]=o[i]??'');return r})}
async function syncCSV(){const data=parseCSV(fs.readFileSync(path.join(__dirname,'data/vinyl_catalog.csv'),'utf8'));const c=await pool.connect();try{await c.query('BEGIN');for(const r of data)await c.query(`INSERT INTO records(artist,album,year,genre,notes)SELECT $1,$2,$3,$4,$5 WHERE NOT EXISTS(SELECT 1 FROM records WHERE LOWER(artist)=LOWER($1) AND LOWER(album)=LOWER($2) AND year IS NOT DISTINCT FROM $3)`,[r.Artist.trim(),r.Album.trim(),r.Year?Number(r.Year):null,r.Genre?.trim()||null,r.Notes?.trim()||null]);await c.query('COMMIT');console.log(`CSV sync checked ${data.length} records.`)}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
app.get('/api/records',async(_,res)=>{try{const{rows}=await pool.query("SELECT * FROM records ORDER BY LOWER(REGEXP_REPLACE(artist,'^(The |A )','')),LOWER(album)");res.json(rows)}catch(e){res.status(500).json({error:'Unable to load records'})}});
app.post('/api/records',requireAdmin,async(req,res)=>{const{artist,album,year,genre,notes}=req.body;if(!artist?.trim()||!album?.trim())return res.status(400).json({error:'Artist and album are required'});try{const{rows}=await pool.query('INSERT INTO records(artist,album,year,genre,notes)VALUES($1,$2,$3,$4,$5)RETURNING *',[artist.trim(),album.trim(),year?Number(year):null,genre?.trim()||null,notes?.trim()||null]);res.status(201).json(rows[0])}catch(e){res.status(500).json({error:'Unable to add record'})}});
app.put('/api/records/:id',requireAdmin,async(req,res)=>{const{artist,album,year,genre,notes}=req.body;if(!artist?.trim()||!album?.trim())return res.status(400).json({error:'Artist and album are required'});try{const{rows}=await pool.query('UPDATE records SET artist=$1,album=$2,year=$3,genre=$4,notes=$5,updated_at=NOW() WHERE id=$6 RETURNING *',[artist.trim(),album.trim(),year?Number(year):null,genre?.trim()||null,notes?.trim()||null,req.params.id]);if(!rows.length)return res.status(404).json({error:'Record not found'});res.json(rows[0])}catch(e){res.status(500).json({error:'Unable to update record'})}});
app.put('/api/records/bulk',requireAdmin,async(req,res)=>{const records=Array.isArray(req.body?.records)?req.body.records:[];if(!records.length)return res.json({updated:0});const c=await pool.connect();try{await c.query('BEGIN');for(const r of records){if(!r.id||!r.artist?.trim()||!r.album?.trim())throw Error('Artist and album are required');await c.query('UPDATE records SET artist=$1,album=$2,year=$3,genre=$4,notes=$5,updated_at=NOW() WHERE id=$6',[r.artist.trim(),r.album.trim(),r.year?Number(r.year):null,r.genre?.trim()||null,r.notes?.trim()||null,r.id])}await c.query('COMMIT');res.json({updated:records.length})}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message||'Unable to save changes'})}finally{c.release()}});
app.delete('/api/records/:id',requireAdmin,async(req,res)=>{try{const r=await pool.query('DELETE FROM records WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Record not found'});res.status(204).end()}catch(e){res.status(500).json({error:'Unable to delete record'})}});
app.get('/{*splat}',(_,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
(async()=>{try{await ensureDatabase();await syncCSV();app.listen(PORT,()=>console.log(`Vinyl collection listening on ${PORT}`))}catch(e){console.error(e);process.exit(1)}})();